/**
 * POST /api/extension/add-product
 * Dedicated endpoint for the "Add to Affiliate OS" Chrome extension.
 *
 * Security:
 * - Only accepts requests with matching X-Extension-Token header
 * - CORS: restricts origin to chrome-extension://* and localhost (dev)
 * - Does NOT use Access-Control-Allow-Origin: *
 * - Token is set via EXTENSION_LOCAL_TOKEN in .env.local
 *   (auto-generated by extension on first install; user must copy to .env.local)
 *
 * If EXTENSION_LOCAL_TOKEN is not set, the endpoint rejects all requests (fail-safe).
 */
import { NextRequest, NextResponse } from 'next/server'
import { createAdmin } from '@/lib/supabase/server'

export const dynamic = 'force-dynamic'

const ALLOWED_ORIGINS = [
  /^chrome-extension:\/\//,
  /^http:\/\/localhost(:\d+)?$/,
  /^http:\/\/127\.0\.0\.1(:\d+)?$/,
]

function corsHeaders(origin: string | null): Record<string, string> {
  const allowed = origin && ALLOWED_ORIGINS.some(r => r.test(origin))
  return {
    'Access-Control-Allow-Origin': allowed ? origin! : 'null',
    'Access-Control-Allow-Methods': 'POST, OPTIONS',
    'Access-Control-Allow-Headers': 'Content-Type, X-Extension-Token',
    'Vary': 'Origin',
  }
}

export async function OPTIONS(req: NextRequest) {
  const origin = req.headers.get('origin')
  return new NextResponse(null, { status: 204, headers: corsHeaders(origin) })
}

export async function POST(req: NextRequest) {
  const origin = req.headers.get('origin')
  const headers = corsHeaders(origin)

  // Token auth — fail-safe: if env not set, reject
  const envToken = process.env.EXTENSION_LOCAL_TOKEN
  if (!envToken) {
    return NextResponse.json(
      { error: 'EXTENSION_LOCAL_TOKEN não configurado no .env.local. Consulte docs/EXTENSION_SETUP.md.' },
      { status: 503, headers }
    )
  }

  const requestToken = req.headers.get('x-extension-token')
  if (!requestToken || requestToken !== envToken) {
    return NextResponse.json(
      { error: 'Token inválido. Sincronize o token da extensão com EXTENSION_LOCAL_TOKEN no .env.local.' },
      { status: 401, headers }
    )
  }

  // Origin check
  const originAllowed = !origin || ALLOWED_ORIGINS.some(r => r.test(origin))
  if (!originAllowed) {
    return NextResponse.json({ error: 'Origem não permitida' }, { status: 403, headers })
  }

  try {
    const body = await req.json() as {
      title?: string
      price?: number
      commissionRate?: number
      affiliateUrl?: string
      imageUrl?: string
      url?: string
      category?: string
      subId?: string
      source?: string
    }

    if (!body.title) {
      return NextResponse.json({ error: 'title é obrigatório' }, { status: 400, headers })
    }
    if (!body.affiliateUrl) {
      return NextResponse.json({ error: 'affiliateUrl é obrigatório' }, { status: 400, headers })
    }

    const admin = createAdmin()

    // Deduplicação: rejeitar se affiliateUrl já cadastrado no workspace
    const { data: existing } = await admin
      .from('products')
      .select('id, title')
      .eq('affiliate_url', body.affiliateUrl)
      .eq('workspace_id', '00000000-0000-0000-0000-000000000001')
      .limit(1)
      .single()

    if (existing) {
      return NextResponse.json(
        { duplicate: true, product: existing, message: 'Produto já cadastrado com esse link de afiliado.' },
        { status: 409, headers }
      )
    }

    const { data, error } = await admin
      .from('products')
      .insert({
        workspace_id: '00000000-0000-0000-0000-000000000001',
        title: body.title,
        price: body.price ?? 0,
        commission_rate: body.commissionRate ?? 0,
        affiliate_url: body.affiliateUrl,
        image_url: body.imageUrl ?? null,
        url: body.url ?? null,
        category: body.category ?? 'geral',
        marketplace: 'shopee',
        // sub_id and source stored in raw_data (no dedicated columns)
        raw_data: {
          source: body.source ?? 'chrome_extension',
          sub_id: body.subId ?? null,
          added_via: 'extension',
        },
      })
      .select()
      .single()

    if (error) return NextResponse.json({ error: error.message }, { status: 500, headers })

    return NextResponse.json({ product: data, message: 'Produto adicionado com sucesso' }, { status: 201, headers })
  } catch (err) {
    return NextResponse.json({ error: String(err) }, { status: 500, headers })
  }
}
